### ISSUE TITLE
Lag on switching gametypes

### ISSUE THREAD

**Issue by dancing-ipsum** [PEMapModder/LegionPE-Public-Resources#29]
Players sometimes disconnects when joining any gametype from lobby or coming back to lobby from any gametype.

**Comment by DunxGit** [comment]
I experience this bug as well

**Comment by dancing-ipsum** [comment]
it's getting annoying stop spamming my mailbox

**Comment by PEMapModder** [comment]
You can choose the click the "Unwatch" button on the top of this page. It is a GitHub feature that automatically sends you info. You can choose to unsubscribe it from your GitHub settings. We didn't send it.

Anyway, regarding your issue, it is an issue limited to MCPE `0.10.5`. It is because MCPE crashes when switching between adventure and survival. The issue should have been fixed by Mojang in `0.11`.

We use survival mode in spleef to allow breaking blocks, and adventure mode in KitPvP to disallow breaking cobwebs.
We will not fix this issue as this isn't our problem, we can't fix it at all and it won't last in future MCPE editions.
